weaviate/weaviate-helm

weaviate/Chart.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/deployment.yaml
weaviate/values.yaml

Added replication to the deployments.
Added default value 1 to `values.yaml`.
Changed chart version to `10.0.1`

Add replication value for weaviate and contextionary

---

weaviate/Chart.yaml
weaviate/templates/collectorProxyDeployment.yaml

Added liveness and readiness probes.

Add live and ready probes to optional collector deployment

---

weaviate/templates/transformersInferenceDeployment.yaml
weaviate/values.yaml

gh-33 support CUDA on transformers inference container

---

weaviate/Chart.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/weaviateConfigMap.yaml
weaviate/values.yaml

gh-36 move contextionary into modules

---

.travis.yml
weaviate/Chart.yaml
weaviate/templates/_helpers.tpl
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/qnaTransformersService.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

gh-38 Add support for qna-transformers module

---

weaviate/Chart.yaml
weaviate/templates/_helpers.tpl
weaviate/templates/img2vecKerasDeployment.yaml
weaviate/templates/img2vecKerasService.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Closes #41 
Closes #42 
Closes #44

Add support for image module and external inference services

---

weaviate/Chart.yaml
weaviate/templates/weaviatePersistentVolumeClaim.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

gh-45 Add check for persistent volume claim existance

---

.cicd/test.sh
weaviate/templates/_helpers.tpl

gh-55 Fix enable_modules setting when transformers, qna , ner and spellcheck modules are turned on

---

weaviate/templates/collectorProxyDeployment.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Add nodeSelector, affinity and tolerations to all deployments and stateful sets.

feat (chart): Add nodeSelector, affinity and tolerations 

---

README.md

last pull request @bobvanluijt

from semi.technology to weaviate.io

---

.cicd/release.sh
.travis.yml
rbac-config.yaml
weaviate/Chart.yaml
weaviate/values.yaml

Reverts semi-technologies/weaviate-helm#80

Revert "Helm remote repo with travis ci"

---

weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/sumTransformersDeployment.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/values.yaml

add NVIDIA_DRIVER_CAPABILITIES env var for CUDA

---

weaviate/templates/collectorProxyConfigMap.yaml
weaviate/templates/collectorProxyDeployment.yaml
weaviate/templates/collectorProxyService.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/contextionaryService.yaml
weaviate/templates/gcsSecret.yaml
weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/img2vecNeuralService.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/multi2vecClipService.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/nerTransformersService.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/qnaTransformersService.yaml
weaviate/templates/s3Secret.yaml
weaviate/templates/sumTransformersDeployment.yaml
weaviate/templates/sumTransformersService.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/textSpellcheckService.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/templates/transformersInferenceService.yaml
weaviate/templates/weaviateConfigMap.yaml
weaviate/templates/weaviateHeadlessService.yaml
weaviate/templates/weaviateSecretCohere.yaml
weaviate/templates/weaviateSecretHuggingFace.yaml
weaviate/templates/weaviateSecretOpenAI.yaml
weaviate/templates/weaviateService.yaml
weaviate/templates/weaviateStatefulset.yaml

This is also needed for creating an application CRD, which is a requirement for GCP marketplace.

Fix #117 apply recommended k8s labels

---

weaviate/values.yaml

Environment variable `GOMEMLIMT` should be `GOMEMLIMIT`

Fix typo in comment

---

weaviate/templates/weaviateStatefulset.yaml

Fix for duplicate CLUSTER_GOSSIP_BIND_PORT and CLUSTER_DATA_BIND_PORT environment variables

---

.cicd/test.sh
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/sumTransformersDeployment.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

add imagePullPolicy to all deployments

---

.cicd/test.sh
weaviate/Chart.yaml
weaviate/templates/weaviateSecretOpenAI.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Add support for AZURE_APIKEY in OpenAI modules

---

.cicd/test.sh
weaviate/templates/_helpers.tpl
weaviate/templates/gpt4allInferenceDeployment.yaml
weaviate/templates/gpt4allInferenceService.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Support for `text2vec-gpt4all` module.

Support for text2vec-gpt4all module

---

weaviate/values.yaml

Remove duplicate fullnameOverride from text2vec-contextionary module

Remove duplicate fullnameOverride from module

---

.cicd/test.sh
weaviate/templates/weaviateServiceGRPC.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Changed the default type of `weaviate-grpc` service to `NodePort`

Changed default K8s gRPC Service type to NodePort

---

.cicd/test.sh
weaviate/Chart.yaml
weaviate/templates/_helpers.tpl
weaviate/templates/apiKeyAnyscaleSecret.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

This PR adds support for `generative-anyscale` module

Add support for generative-anyscale module

---

weaviate/templates/awsSecret.yaml

Fix adding empty weaviate-aws secret

---

weaviate/Chart.yaml
weaviate/templates/contextionaryPodDisruptionBudget.yaml
weaviate/templates/gpt4allPodDisruptionBudget.yaml
weaviate/templates/img2vecPodDisruptionBudget.yaml
weaviate/templates/multi2vecBindPodDisruptionBudget.yaml
weaviate/templates/multi2vecClipPodDisruptionBudget.yaml
weaviate/templates/nerTransformersPodDisruptionBudget.yaml
weaviate/templates/qnaTransformersPodDisruptionBudget.yaml
weaviate/templates/rerankerTransformersPodDisruptionBudget.yaml
weaviate/templates/sumTransformersPodDisruptionBudget.yaml
weaviate/templates/textSpellcheckPodDisruptionBudget.yaml
weaviate/templates/transformersInferencePodDisruptionBudget.yaml
weaviate/templates/weaviatePodDisruptionBudget.yaml
weaviate/values.yaml

Add support for podDisruptionBudgets

---

.gitignore
weaviate/templates/weaviateRuntimeOverrides.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

PR adds support for `runtime-overrides` config. Related PRs on weaviate 
1. https://github.com/weaviate/weaviate/pull/7501
2. https://github.com/weaviate/weaviate/pull/7344
3. https://github.com/weaviate/weaviate/pull/7573

feat(runtime-overrides): Add support for runtime overrides configmap
