weaviate/weaviate-helm

.gitignore
weaviate/Chart.yaml
weaviate/templates/deployment.yaml
weaviate/templates/weaviateConfigMap.yaml
weaviate/values.yaml

very simple additon in the `values.yaml`  https://github.com/semi-technologies/weaviate-helm/blob/add-optional-configmap/weaviate/values.yaml#L49-L51
Next to the values for authentication and authorization a custom config map also needs to contain other values like service discovery info. This is maybe not the most end user friendly but should do for now.

Add optional configmap

---

README.md
weaviate/Chart.yaml
weaviate/templates/collectorProxyConfigMap.yaml
weaviate/templates/collectorProxyDeployment.yaml
weaviate/templates/collectorProxyService.yaml
weaviate/values.yaml

I tested it against one of my clusters. 
It can be configured over the values yaml:
```
collector_proxy:
enabled: false
tag: latest
weaviate_enterprise_token: ""
weaviate_enterprise_project: ""
service:
name: "usage-proxy"
port: 80
type: LoadBalancer
```
If enabled there are 3 new resources created:
- The deployment for the collector
- The service for the collector
- The configmap for the collector

Add collector proxy as option to weavaite chart, bump up chart version

---

weaviate/Chart.yaml
weaviate/templates/collectorProxyDeployment.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/values.yaml

As discussed with @etiennedi:
`values.yaml` currently allows for `nodeSelector`, `affinity`, and `tolerations` configuration which affects how k8s schedules **all** pods in the Weaviate chart.
However, as workloads have quite different hardware needs (e.g. GPUs while building the index; lots of memory while serving requests), it would be useful to be able to direct scheduling on a per module basis.
- Add `nodeSelector`, `affinity`, and `tolerations` sections to each of the modules' deployment files
- We fall back to the global configuration if no per-module configuration is supplied
- Change `values.yaml` to document the new functionality and show an example
It could be argued we should merge global and per-module scheduler configuration. However, overriding is more expressive because any …

Allow for per-module pod scheduling hints

---

weaviate/templates/transformersInferenceDeployment.yaml
weaviate/values.yaml

For those of us who are building our custom text2vec-transformer models, the probes' initialDelaySeconds might need to be adjusted (increased), as some of these models can be really heavy to load.
The readinessProbe's initialDelaySeconds being hard-coded to 3 seconds was especially an issue, so I have made the initial delay configurable for the two probes of the text2vec-transformers module, so anybody can adjust them depending on the load time of their transformer models.

Making the probes' initiaDelaySeconds configurable for the text2vec-transformers module

---

weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Fixes #77 - Weaviate v1.14.0 supports Prometheus scraping, so you can have Grafana dashboards to monitor Weaviate.
Unfortunately for Prometheus to be able to scrape the exposed endpoint (/metrics on port 2112), that port need to be added to the StatefulSet's container port.
This changes adds that container port (2112) to the Helm chart, in case the `PROMETHEUS_MONITORING_ENABLED` env variable is set to true (which is the same env variable the Weaviate app watches out for).
Once that env variable is set, to setup the Prometheus scarping config to discover your Weaviate endpoints (assuming it is running in the `weaviate` namespace), add the following to your Prometheus config:
```
- job_name: weaviate
scrape_interval: 5s
scrape_timeout: 5s
scheme: http
metrics_path: /metrics …
```

Fixing gh77 - Missing support for Prometheus scraping

---

weaviate/values.yaml

use kubernetes cluster's default storageClass for Weaviate's PVs, 

---

weaviate/README.md

The chart README will be shown here: https://artifacthub.io/packages/helm/weaviate/weaviate
It was due for an update since it also referred to semi.technology and had old instructions on how to install the helm chart

Update the chart README

---

artifacthub-repo.yml

This will allow us to have a listing on artifacthub.io and have an official and verified publisher badge
This is the helm repo listing that was created: https://artifacthub.io/packages/helm/weaviate/weaviate
I can transfer the listing to weaviate org after someone from weaviate team creates the weaviate org in artifacthub.io

Add artifacthub-repo.yml for official helm chart

---

weaviate/templates/weaviateStatefulset.yaml

Previously the serviceName was incorrectly set to the weaviate service however that makes it not possible to use the stable networking ID properties of the StatefulSet.
This change fixes it by pointing the StatefulSet.serviceName to point to the weaviate-headless service instead
Fixes #124

StatefulSet set serviceName to headless svc

---

.cicd/test.sh
weaviate/Chart.yaml
weaviate/templates/weaviateServiceMonitor.yaml
weaviate/values.yaml

Define `serviceMonitor` prometheus CRD resource to scrape metrics (disabled by default). Here is the rendered manifest:
```
helm template . --set env.PROMETHEUS_MONITORING_ENABLED=true --set serviceMonitor.enabled=true
...
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
name: weaviate
labels:
name: weaviate
app: weaviate
app.kubernetes.io/name: weaviate
app.kubernetes.io/managed-by: helm
spec:
jobLabel: weaviate
selector:
matchLabels:
app.kubernetes.io/name: weaviate
app.kubernetes.io/managed-by: helm
namespaceSelector:
matchNames:
- "weaviate"
endpoints:
- targetPort: metrics
path: /metrics
interval: 30s
scrapeTimeout: 10s
```

Define prometheus service monitor to scrape metrics

---

.cicd/test.sh
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

For a project we keep our secrets in AWS, and parse them as kubernetes secrets with the secret store CSI driver (https://secrets-store-csi-driver.sigs.k8s.io). For this to actually work you need a volume and volumeMount that use this driver to make sure the secrets are fetched from AWS, en the secret resource is created. 
Since we want to use an AWS stored secret for the AUTHENTICATION_APIKEY_ALLOWED_KEYS, env var, we thus need a pod with the mentioned volume and volumeMount. 
We now circumvent this issue by just spinning up a pod with the required volume, which is indefinitely sleeping, but it would probably be cleaner if we could just add it to the Weaviate StatefulSet. 
So hereby a PR to add functionality to allow any number of extra volumes or volumeMounts.

Allow extra volumes and volumeMounts in the weaviate StatefulSet

---

.cicd/test.sh
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/weaviateConfigMap.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Closes #175 - Please see the issue for the exact details on the issue this is fixing.
This PR changes two things:
1. It changes the default `CLUSTER_JOIN` (and other k8s-internal hostnames) to be fully qualified domain names. The difference from the existing configuration is the addition of an additional `.` at the end of the hostnames used (i.e `svc.cluster.local` becomes `svc.cluster.local.`
2. It abstracts the actual value of the internal cluster domain to a value in the helm chart, so that users can configure it to whatever they need. 
- This is common practice in many helm charts, see examples from bitnami charts [here](https://github.com/bitnami/charts/blob/main/bitnami/milvus/values.yaml#L43) and [here](https://github.com/bitnami/charts/blob/main/bitnami/cassandra/values.yaml#L43)

Use a fully qualified cluster domain throughout the configuration

---

weaviate/templates/_helpers.tpl
weaviate/values.yaml

Use BootstrapExpect to specify the number of voters

Configure cluster with both voting and non-voting members. 

---

.cicd/test.sh
weaviate/Chart.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Currently, it is only possible to set [PodSecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#podsecuritycontext-v1-core) for Weaviate StatefulSet, but it's not possible to set security context for the main `weaviate` container, which is backed by [SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#securitycontext-v1-core) object and contains additional configuration parameters extending the `PodSecurityContext`, allowing fine-granular overwrites on the container level.
This PR:
- introduces a new value `containerSecurityContext` in `values.yaml`
- propagates the value to the `securityContext` of the `weaviate` container
- adds a test to verify new field
- bumps chart version to `16.8.2`

Make securityContext configurable for weaviate container

---

weaviate/templates/apiKeyCohereSecret.yaml
weaviate/templates/apiKeyHuggingFaceSecret.yaml
weaviate/templates/apiKeyJinaAISecret.yaml
weaviate/templates/apiKeyOpenAISecret.yaml
weaviate/templates/apiKeyPaLMSecret.yaml
weaviate/templates/awsSecret.yaml
weaviate/templates/backupAzureSecret.yaml
weaviate/templates/backupGcsSecret.yaml
weaviate/templates/backupS3Secret.yaml
weaviate/templates/contextionaryDeployment.yaml
weaviate/templates/gpt4allInferenceDeployment.yaml
weaviate/templates/img2vecNeuralDeployment.yaml
weaviate/templates/multi2vecBindDeployment.yaml
weaviate/templates/multi2vecClipDeployment.yaml
weaviate/templates/nerTransformersDeployment.yaml
weaviate/templates/qnaTransformersDeployment.yaml
weaviate/templates/rerankerTransformersDeployment.yaml
weaviate/templates/sumTransformersDeployment.yaml
weaviate/templates/textSpellcheckDeployment.yaml
weaviate/templates/transformersInferenceDeployment.yaml
weaviate/templates/weaviateConfigMap.yaml
weaviate/templates/weaviateHeadlessService.yaml
weaviate/templates/weaviateService.yaml
weaviate/templates/weaviateServiceGRPC.yaml
weaviate/templates/weaviateServiceMonitor.yaml
weaviate/templates/weaviateStatefulset.yaml

* Previously, it was hard coded to be `helm`
* But on GKE, this changes to `Helm` with capital `H`
* This causes a mismatch between the `Service` and the `ServiceMonitor`
* Because the components labels changes to `Helm`
* But, the ServiceMonitor `spec.selector.matchLabels` remains `helm` with lowercase `h`
* So, to avoid this, I think it's better to set them all to `{{ .Release.Service }} instead
* refer to #192

fix: fix the "app.kubernetes.io/managed-by" label

---

.cicd/test.sh
weaviate/values.yaml

This PR enables gRPC service by default and changes it's type to `LoadBalancer`.

Change gRPC service type to LoadBalancer and enable it by default

---

.cicd/test.sh
weaviate/Chart.yaml
weaviate/templates/weaviateStatefulset.yaml
weaviate/values.yaml

Add ability to configure probe types and probes. This is particularly useful in mTLS scenarios where an exec command probe is desired.
Usage:
```yaml
startupProbe:
enabled: true
probeType: exec
probe:
exec:
command: ["/bin/sh", "-c", "wget --spider --server-response --tries=1 --timeout=30 -o /dev/null localhost:8080/v1/.well-known/ready"]
livenessProbe:
probeType: exec
probe:
exec:
command: ["/bin/sh", "-c", "wget --spider --server-response --tries=1 --timeout=30 -o /dev/null localhost:8080/v1/.well-known/live"]
readinessProbe:
probeType: exec
probe:
exec:
command: ["/bin/sh", "-c", "wget --spider --server-response --tries=1 --timeout=30 -o /dev/null localhost:8080/v1/.well-known/ready"]
```

Add ability to configure probe types and probes

---

weaviate/templates/weaviateStatefulset.yaml

STANDALONE_MODE was an experimental setting in Weaviate 0.x, the environment variable is not used anymore in the current code base. Fixes #229.

Delete unused environment variable STANDALONE_MODE

---

weaviate/templates/weaviateService.yaml
weaviate/templates/weaviateServiceMonitor.yaml
weaviate/values.yaml

Currently, the ServiceMonitor uses a set of labels which match all the three existing services: weaviate, weaviate-headless and weaviate-grpc. This ends up into importing three different targets in Prometheus, multiplying all the metrics by 3. This PR adds a new label monitoring: enabled in the weaviate service only if serviceMonitor is enabled (and the PROMETHEUS env variable too). Like this, only one target will be imported, reducing the number of metrics.

Add label to weaviate service for monitoring.

---

weaviate/templates/_helpers.tpl

RAFT_JOIN is creating with a hard coded value of "weaviate" and pod number, eg for a single node cluster: "weaviate-0". Updated the _helpers.tpl so that we set and use the pod name value more explicitly as pod_prefix.

Updated RAFT_JOIN to use pod_prefix value

---

weaviate/values.yaml

The configuration of RBAC can be done either via the config.yaml file or via environment variables. To keep it consistent with the existing authZ and authN config values, it is disabled by default and each of the available values gets referenced in the values.yaml.

Document rbac's variables.
